# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

 desc "Retrieve all the certificates for all targets and configures your machine to compile against devices"
  lane :setup do

    # Bink

    match(type: "appstore", app_identifier: "com.bink.localhero", readonly: true)
    match(type: "development", app_identifier: "com.bink.localhero.alpha", readonly: true)
    match(type: "adhoc", app_identifier: "com.bink.localhero.beta", readonly: true)

    # For MR builds to Testflight
    match(type: "appstore", app_identifier: "com.bink.localhero.beta", readonly: true)

  end